[Log]
Level = 'warn'

[WebServer]
AllowOrigins = '\*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[[EVM]]
ChainID = '11155111'

[[EVM.Nodes]]
Name = 'Sepolia'
WSURL = 'wss://eth-sepolia.g.alchemy.com/v2/ZKG9vwIBS-DxJPeEVFCvJxOUORRkt-aG'
HTTPURL = 'https://eth-sepolia.g.alchemy.com/v2/ZKG9vwIBS-DxJPeEVFCvJxOUORRkt-aG'

