type = "directrequest"
schemaVersion = 1
name = "clr-ipfs-decrypt-and-validate-v0.0.1"
externalJobID = "6fde68e1-ca75-4a41-b195-e3ea02a892aa"
forwardingAllowed = false
maxTaskDuration = "0s"
contractAddress = "0x3Eb267a7aDDAD23ba0DB19Ed212506C275C53B81"
minContractPaymentLinkJuels = "0"
observationSource = """
    decode_log   [type=ethabidecodelog
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type=cborparse data="$(decode_log.data)"]
    fetch        [type=bridge name="clr-ea-v0" requestData="{\\"id\\": $(jobSpec.externalJobID), \\"data\\": { \\"ipfs_cid\\": $(decode_cbor.ipfs_cid), \\"decryption_key\\": $(decode_cbor.decryption_key) }}"]
    parse        [type=jsonparse path="data,result" data="$(fetch)"]
    encode_data  [type=ethabiencode abi="(bytes32 requestId,bytes32 hash)" data="{\\"requestId\\": $(decode_log.requestId),\\"hash\\": $(parse) }"]
    encode_tx    [type=ethabiencode
                  abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"]
    submit_tx    [type=ethtx to="0x3Eb267a7aDDAD23ba0DB19Ed212506C275C53B81" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> parse -> encode_data -> encode_tx -> submit_tx
"""